// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// value_map
std::map<int, std::vector<int> > value_map(std::vector<int> x);
RcppExport SEXP _rexmap_value_map(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(value_map(x));
    return rcpp_result_gen;
END_RCPP
}
// partid_to_fastqid
std::map<int, std::vector<int> > partid_to_fastqid(std::vector<int> dada_map, std::vector<int> derep_map);
RcppExport SEXP _rexmap_partid_to_fastqid(SEXP dada_mapSEXP, SEXP derep_mapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type dada_map(dada_mapSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type derep_map(derep_mapSEXP);
    rcpp_result_gen = Rcpp::wrap(partid_to_fastqid(dada_map, derep_map));
    return rcpp_result_gen;
END_RCPP
}
// consensus_sequence
std::string consensus_sequence(std::vector<std::string> seqs);
RcppExport SEXP _rexmap_consensus_sequence(SEXP seqsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type seqs(seqsSEXP);
    rcpp_result_gen = Rcpp::wrap(consensus_sequence(seqs));
    return rcpp_result_gen;
END_RCPP
}
// hamming
int hamming(std::string s1, std::string s2);
RcppExport SEXP _rexmap_hamming(SEXP s1SEXP, SEXP s2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< std::string >::type s2(s2SEXP);
    rcpp_result_gen = Rcpp::wrap(hamming(s1, s2));
    return rcpp_result_gen;
END_RCPP
}
// compare_alignment
IntegerVector compare_alignment(std::string s1, std::string s2);
RcppExport SEXP _rexmap_compare_alignment(SEXP s1SEXP, SEXP s2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< std::string >::type s2(s2SEXP);
    rcpp_result_gen = Rcpp::wrap(compare_alignment(s1, s2));
    return rcpp_result_gen;
END_RCPP
}
// create_scoring_matrix
std::vector<std::vector<int>> create_scoring_matrix(Rcpp::IntegerVector& alignment_scores);
RcppExport SEXP _rexmap_create_scoring_matrix(SEXP alignment_scoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type alignment_scores(alignment_scoresSEXP);
    rcpp_result_gen = Rcpp::wrap(create_scoring_matrix(alignment_scores));
    return rcpp_result_gen;
END_RCPP
}
// c_align_paired_sequence_and_quality
Rcpp::List c_align_paired_sequence_and_quality(Rcpp::List& sequences, Rcpp::List& qualities, Rcpp::IntegerVector& alignment_scores, std::vector<std::vector<unsigned int>>& match_quality_merging_map, std::vector<std::vector<unsigned int>>& mismatch_quality_merging_map);
RcppExport SEXP _rexmap_c_align_paired_sequence_and_quality(SEXP sequencesSEXP, SEXP qualitiesSEXP, SEXP alignment_scoresSEXP, SEXP match_quality_merging_mapSEXP, SEXP mismatch_quality_merging_mapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type qualities(qualitiesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type alignment_scores(alignment_scoresSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<unsigned int>>& >::type match_quality_merging_map(match_quality_merging_mapSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<unsigned int>>& >::type mismatch_quality_merging_map(mismatch_quality_merging_mapSEXP);
    rcpp_result_gen = Rcpp::wrap(c_align_paired_sequence_and_quality(sequences, qualities, alignment_scores, match_quality_merging_map, mismatch_quality_merging_map));
    return rcpp_result_gen;
END_RCPP
}
// load_posterior
std::vector< std::vector<int> > load_posterior(std::string filename);
RcppExport SEXP _rexmap_load_posterior(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(load_posterior(filename));
    return rcpp_result_gen;
END_RCPP
}
// string_to_vector_str
std::vector<std::string> string_to_vector_str(std::string& str);
RcppExport SEXP _rexmap_string_to_vector_str(SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string& >::type str(strSEXP);
    rcpp_result_gen = Rcpp::wrap(string_to_vector_str(str));
    return rcpp_result_gen;
END_RCPP
}
// string_to_vector_int
std::vector<int> string_to_vector_int(std::string& str);
RcppExport SEXP _rexmap_string_to_vector_int(SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string& >::type str(strSEXP);
    rcpp_result_gen = Rcpp::wrap(string_to_vector_int(str));
    return rcpp_result_gen;
END_RCPP
}
// C_mergepairs
Rcpp::List C_mergepairs(std::string s1, std::string s2, std::string q1, std::string q2, std::string posterior_match_file, std::string posterior_mismatch_file, int match, int mismatch, int gap_p);
RcppExport SEXP _rexmap_C_mergepairs(SEXP s1SEXP, SEXP s2SEXP, SEXP q1SEXP, SEXP q2SEXP, SEXP posterior_match_fileSEXP, SEXP posterior_mismatch_fileSEXP, SEXP matchSEXP, SEXP mismatchSEXP, SEXP gap_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< std::string >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< std::string >::type q1(q1SEXP);
    Rcpp::traits::input_parameter< std::string >::type q2(q2SEXP);
    Rcpp::traits::input_parameter< std::string >::type posterior_match_file(posterior_match_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type posterior_mismatch_file(posterior_mismatch_fileSEXP);
    Rcpp::traits::input_parameter< int >::type match(matchSEXP);
    Rcpp::traits::input_parameter< int >::type mismatch(mismatchSEXP);
    Rcpp::traits::input_parameter< int >::type gap_p(gap_pSEXP);
    rcpp_result_gen = Rcpp::wrap(C_mergepairs(s1, s2, q1, q2, posterior_match_file, posterior_mismatch_file, match, mismatch, gap_p));
    return rcpp_result_gen;
END_RCPP
}
// c_create_flat_index
std::unordered_map<std::string, unsigned int> c_create_flat_index(unsigned int row, unsigned int column, unsigned int num_columns);
RcppExport SEXP _rexmap_c_create_flat_index(SEXP rowSEXP, SEXP columnSEXP, SEXP num_columnsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type row(rowSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type column(columnSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type num_columns(num_columnsSEXP);
    rcpp_result_gen = Rcpp::wrap(c_create_flat_index(row, column, num_columns));
    return rcpp_result_gen;
END_RCPP
}
// c_alignmentgrid_fill_first_row
std::unordered_map<std::string, std::vector<int>> c_alignmentgrid_fill_first_row(std::vector<int>& score, std::vector<int>& path, unsigned int num_rows, unsigned int num_columns);
RcppExport SEXP _rexmap_c_alignmentgrid_fill_first_row(SEXP scoreSEXP, SEXP pathSEXP, SEXP num_rowsSEXP, SEXP num_columnsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int>& >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type path(pathSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type num_rows(num_rowsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type num_columns(num_columnsSEXP);
    rcpp_result_gen = Rcpp::wrap(c_alignmentgrid_fill_first_row(score, path, num_rows, num_columns));
    return rcpp_result_gen;
END_RCPP
}
// c_alignmentgrid_fill_first_column
std::unordered_map<std::string, std::vector<int>> c_alignmentgrid_fill_first_column(std::vector<int>& score, std::vector<int>& path, int num_rows, int num_columns, int gap_penalty);
RcppExport SEXP _rexmap_c_alignmentgrid_fill_first_column(SEXP scoreSEXP, SEXP pathSEXP, SEXP num_rowsSEXP, SEXP num_columnsSEXP, SEXP gap_penaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int>& >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type path(pathSEXP);
    Rcpp::traits::input_parameter< int >::type num_rows(num_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type num_columns(num_columnsSEXP);
    Rcpp::traits::input_parameter< int >::type gap_penalty(gap_penaltySEXP);
    rcpp_result_gen = Rcpp::wrap(c_alignmentgrid_fill_first_column(score, path, num_rows, num_columns, gap_penalty));
    return rcpp_result_gen;
END_RCPP
}
// c_alignmentgrid_fill_other
std::unordered_map<std::string, std::vector<int>> c_alignmentgrid_fill_other(std::vector<int>& score, std::vector<int>& path, Rcpp::List& sequences, std::vector<std::vector<int>>& scoring_matrix, int gap_penalty);
RcppExport SEXP _rexmap_c_alignmentgrid_fill_other(SEXP scoreSEXP, SEXP pathSEXP, SEXP sequencesSEXP, SEXP scoring_matrixSEXP, SEXP gap_penaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int>& >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type path(pathSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<int>>& >::type scoring_matrix(scoring_matrixSEXP);
    Rcpp::traits::input_parameter< int >::type gap_penalty(gap_penaltySEXP);
    rcpp_result_gen = Rcpp::wrap(c_alignmentgrid_fill_other(score, path, sequences, scoring_matrix, gap_penalty));
    return rcpp_result_gen;
END_RCPP
}
// c_alignmentgrid_best_path
std::unordered_map<std::string, std::vector<int>> c_alignmentgrid_best_path(Rcpp::List& sequences, std::vector<std::vector<int>>& scoring_matrix, int gap_penalty);
RcppExport SEXP _rexmap_c_alignmentgrid_best_path(SEXP sequencesSEXP, SEXP scoring_matrixSEXP, SEXP gap_penaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<int>>& >::type scoring_matrix(scoring_matrixSEXP);
    Rcpp::traits::input_parameter< int >::type gap_penalty(gap_penaltySEXP);
    rcpp_result_gen = Rcpp::wrap(c_alignmentgrid_best_path(sequences, scoring_matrix, gap_penalty));
    return rcpp_result_gen;
END_RCPP
}
// c_merge_paired_sequence_and_quality
Rcpp::List c_merge_paired_sequence_and_quality(Rcpp::List& sequence, Rcpp::List& quality, std::vector<int>& grid_path, std::vector<std::vector<unsigned int>>& match_quality_merging_map, std::vector<std::vector<unsigned int>>& mismatch_quality_merging_map);
RcppExport SEXP _rexmap_c_merge_paired_sequence_and_quality(SEXP sequenceSEXP, SEXP qualitySEXP, SEXP grid_pathSEXP, SEXP match_quality_merging_mapSEXP, SEXP mismatch_quality_merging_mapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type sequence(sequenceSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type quality(qualitySEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type grid_path(grid_pathSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<unsigned int>>& >::type match_quality_merging_map(match_quality_merging_mapSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<unsigned int>>& >::type mismatch_quality_merging_map(mismatch_quality_merging_mapSEXP);
    rcpp_result_gen = Rcpp::wrap(c_merge_paired_sequence_and_quality(sequence, quality, grid_path, match_quality_merging_map, mismatch_quality_merging_map));
    return rcpp_result_gen;
END_RCPP
}
// to_int
int to_int(char& nt);
RcppExport SEXP _rexmap_to_int(SEXP ntSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< char& >::type nt(ntSEXP);
    rcpp_result_gen = Rcpp::wrap(to_int(nt));
    return rcpp_result_gen;
END_RCPP
}
// C_nwalign
Rcpp::CharacterVector C_nwalign(std::string s1, std::string s2, int match, int mismatch, int indel);
RcppExport SEXP _rexmap_C_nwalign(SEXP s1SEXP, SEXP s2SEXP, SEXP matchSEXP, SEXP mismatchSEXP, SEXP indelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< std::string >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< int >::type match(matchSEXP);
    Rcpp::traits::input_parameter< int >::type mismatch(mismatchSEXP);
    Rcpp::traits::input_parameter< int >::type indel(indelSEXP);
    rcpp_result_gen = Rcpp::wrap(C_nwalign(s1, s2, match, mismatch, indel));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rexmap_value_map", (DL_FUNC) &_rexmap_value_map, 1},
    {"_rexmap_partid_to_fastqid", (DL_FUNC) &_rexmap_partid_to_fastqid, 2},
    {"_rexmap_consensus_sequence", (DL_FUNC) &_rexmap_consensus_sequence, 1},
    {"_rexmap_hamming", (DL_FUNC) &_rexmap_hamming, 2},
    {"_rexmap_compare_alignment", (DL_FUNC) &_rexmap_compare_alignment, 2},
    {"_rexmap_create_scoring_matrix", (DL_FUNC) &_rexmap_create_scoring_matrix, 1},
    {"_rexmap_c_align_paired_sequence_and_quality", (DL_FUNC) &_rexmap_c_align_paired_sequence_and_quality, 5},
    {"_rexmap_load_posterior", (DL_FUNC) &_rexmap_load_posterior, 1},
    {"_rexmap_string_to_vector_str", (DL_FUNC) &_rexmap_string_to_vector_str, 1},
    {"_rexmap_string_to_vector_int", (DL_FUNC) &_rexmap_string_to_vector_int, 1},
    {"_rexmap_C_mergepairs", (DL_FUNC) &_rexmap_C_mergepairs, 9},
    {"_rexmap_c_create_flat_index", (DL_FUNC) &_rexmap_c_create_flat_index, 3},
    {"_rexmap_c_alignmentgrid_fill_first_row", (DL_FUNC) &_rexmap_c_alignmentgrid_fill_first_row, 4},
    {"_rexmap_c_alignmentgrid_fill_first_column", (DL_FUNC) &_rexmap_c_alignmentgrid_fill_first_column, 5},
    {"_rexmap_c_alignmentgrid_fill_other", (DL_FUNC) &_rexmap_c_alignmentgrid_fill_other, 5},
    {"_rexmap_c_alignmentgrid_best_path", (DL_FUNC) &_rexmap_c_alignmentgrid_best_path, 3},
    {"_rexmap_c_merge_paired_sequence_and_quality", (DL_FUNC) &_rexmap_c_merge_paired_sequence_and_quality, 5},
    {"_rexmap_to_int", (DL_FUNC) &_rexmap_to_int, 1},
    {"_rexmap_C_nwalign", (DL_FUNC) &_rexmap_C_nwalign, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_rexmap(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
