# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

value_map <- function(x) {
    .Call('_rexmap_value_map', PACKAGE = 'rexmap', x)
}

partid_to_fastqid <- function(dada_map, derep_map) {
    .Call('_rexmap_partid_to_fastqid', PACKAGE = 'rexmap', dada_map, derep_map)
}

consensus_sequence <- function(seqs) {
    .Call('_rexmap_consensus_sequence', PACKAGE = 'rexmap', seqs)
}

hamming <- function(s1, s2) {
    .Call('_rexmap_hamming', PACKAGE = 'rexmap', s1, s2)
}

compare_alignment <- function(s1, s2) {
    .Call('_rexmap_compare_alignment', PACKAGE = 'rexmap', s1, s2)
}

create_scoring_matrix <- function(alignment_scores) {
    .Call('_rexmap_create_scoring_matrix', PACKAGE = 'rexmap', alignment_scores)
}

c_align_paired_sequence_and_quality <- function(sequences, qualities, alignment_scores, match_quality_merging_map, mismatch_quality_merging_map) {
    .Call('_rexmap_c_align_paired_sequence_and_quality', PACKAGE = 'rexmap', sequences, qualities, alignment_scores, match_quality_merging_map, mismatch_quality_merging_map)
}

load_posterior <- function(filename) {
    .Call('_rexmap_load_posterior', PACKAGE = 'rexmap', filename)
}

string_to_vector_str <- function(str) {
    .Call('_rexmap_string_to_vector_str', PACKAGE = 'rexmap', str)
}

string_to_vector_int <- function(str) {
    .Call('_rexmap_string_to_vector_int', PACKAGE = 'rexmap', str)
}

C_mergepairs <- function(s1, s2, q1, q2, posterior_match_file, posterior_mismatch_file, match, mismatch, gap_p) {
    .Call('_rexmap_C_mergepairs', PACKAGE = 'rexmap', s1, s2, q1, q2, posterior_match_file, posterior_mismatch_file, match, mismatch, gap_p)
}

c_create_flat_index <- function(row, column, num_columns) {
    .Call('_rexmap_c_create_flat_index', PACKAGE = 'rexmap', row, column, num_columns)
}

c_alignmentgrid_fill_first_row <- function(score, path, num_rows, num_columns) {
    .Call('_rexmap_c_alignmentgrid_fill_first_row', PACKAGE = 'rexmap', score, path, num_rows, num_columns)
}

c_alignmentgrid_fill_first_column <- function(score, path, num_rows, num_columns, gap_penalty) {
    .Call('_rexmap_c_alignmentgrid_fill_first_column', PACKAGE = 'rexmap', score, path, num_rows, num_columns, gap_penalty)
}

c_alignmentgrid_fill_other <- function(score, path, sequences, scoring_matrix, gap_penalty) {
    .Call('_rexmap_c_alignmentgrid_fill_other', PACKAGE = 'rexmap', score, path, sequences, scoring_matrix, gap_penalty)
}

c_alignmentgrid_best_path <- function(sequences, scoring_matrix, gap_penalty) {
    .Call('_rexmap_c_alignmentgrid_best_path', PACKAGE = 'rexmap', sequences, scoring_matrix, gap_penalty)
}

c_merge_paired_sequence_and_quality <- function(sequence, quality, grid_path, match_quality_merging_map, mismatch_quality_merging_map) {
    .Call('_rexmap_c_merge_paired_sequence_and_quality', PACKAGE = 'rexmap', sequence, quality, grid_path, match_quality_merging_map, mismatch_quality_merging_map)
}

to_int <- function(nt) {
    .Call('_rexmap_to_int', PACKAGE = 'rexmap', nt)
}

C_nwalign <- function(s1, s2, match, mismatch, indel) {
    .Call('_rexmap_C_nwalign', PACKAGE = 'rexmap', s1, s2, match, mismatch, indel)
}

