# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

value_map <- function(x) {
    .Call('_rexmap_value_map', PACKAGE = 'rexmap', x)
}

partid_to_fastqid <- function(dada_map, derep_map) {
    .Call('_rexmap_partid_to_fastqid', PACKAGE = 'rexmap', dada_map, derep_map)
}

consensus_sequence <- function(seqs) {
    .Call('_rexmap_consensus_sequence', PACKAGE = 'rexmap', seqs)
}

hamming <- function(s1, s2) {
    .Call('_rexmap_hamming', PACKAGE = 'rexmap', s1, s2)
}

compare_alignment <- function(s1, s2) {
    .Call('_rexmap_compare_alignment', PACKAGE = 'rexmap', s1, s2)
}

get_merged_qualities <- function(q1char, q2char, merged_qualities) {
    .Call('_rexmap_get_merged_qualities', PACKAGE = 'rexmap', q1char, q2char, merged_qualities)
}

align_seqs_and_quals <- function(sequences, qualities, alignment_scores, merged_qualities_match, merged_qualities_mismatch) {
    .Call('_rexmap_align_seqs_and_quals', PACKAGE = 'rexmap', sequences, qualities, alignment_scores, merged_qualities_match, merged_qualities_mismatch)
}

load_posterior <- function(filename) {
    .Call('_rexmap_load_posterior', PACKAGE = 'rexmap', filename)
}

string_to_vector_str <- function(str) {
    .Call('_rexmap_string_to_vector_str', PACKAGE = 'rexmap', str)
}

string_to_vector_int <- function(str) {
    .Call('_rexmap_string_to_vector_int', PACKAGE = 'rexmap', str)
}

C_mergepairs <- function(s1, s2, q1, q2, posterior_match_file, posterior_mismatch_file, match, mismatch, gap_p) {
    .Call('_rexmap_C_mergepairs', PACKAGE = 'rexmap', s1, s2, q1, q2, posterior_match_file, posterior_mismatch_file, match, mismatch, gap_p)
}

test_calc_score_path_first_row <- function(score, path, ncol) {
    .Call('_rexmap_test_calc_score_path_first_row', PACKAGE = 'rexmap', score, path, ncol)
}

test_calc_score_path_first_column <- function(score, path, nrow, ncol, gap_p) {
    .Call('_rexmap_test_calc_score_path_first_column', PACKAGE = 'rexmap', score, path, nrow, ncol, gap_p)
}

test_calc_score_path_other <- function(score, path, sequences, align_scores, gap_p) {
    .Call('_rexmap_test_calc_score_path_other', PACKAGE = 'rexmap', score, path, sequences, align_scores, gap_p)
}

test_find_best_scoring_path <- function(sequences, scoring_matrix, gap_p) {
    .Call('_rexmap_test_find_best_scoring_path', PACKAGE = 'rexmap', sequences, scoring_matrix, gap_p)
}

test_merge_by_path_backtrack <- function(path, sequences, qualities, merged_qualities_match, merged_qualities_mismatch) {
    .Call('_rexmap_test_merge_by_path_backtrack', PACKAGE = 'rexmap', path, sequences, qualities, merged_qualities_match, merged_qualities_mismatch)
}

to_int <- function(nt) {
    .Call('_rexmap_to_int', PACKAGE = 'rexmap', nt)
}

create_scoring_matrix <- function(match, mismatch) {
    .Call('_rexmap_create_scoring_matrix', PACKAGE = 'rexmap', match, mismatch)
}

create_flat_indexes <- function(column, row, ncol) {
    .Call('_rexmap_create_flat_indexes', PACKAGE = 'rexmap', column, row, ncol)
}

C_nwalign <- function(s1, s2, match, mismatch, indel) {
    .Call('_rexmap_C_nwalign', PACKAGE = 'rexmap', s1, s2, match, mismatch, indel)
}

